import logging
from pathlib import Path
from typing import Dict, Any, List, Optional
import json
import uuid

from finer.services.converter import DocumentConverter
from finer.llm import LLMClient
from finer.parsing.slang import SlangMapper

class PerceptionOrchestrator:
    """
    Orchestrates the conversion of heterogenous research content into the 
    standardized Research Object (Step 1 of the Reinforced Cognition Loop).
    """

    def __init__(self, llm_provider: str = "openai"):
        self.converter = DocumentConverter()
        self.slang_mapper = SlangMapper()
        self.llm = LLMClient.auto()

    def process_content(self, source_path: Path, content_id: str, content_type: str) -> Optional[Dict[str, Any]]:
        """
        Takes raw content and produces a structured research object.
        """
        logging.info(f"Processing content of type [{content_type}] at {source_path}...")

        # 1. Convert/Convert to text/markdown as primary source
        # For images, we can also keep the image path for VLM perception.
        markdown_text = self.converter.convert_to_markdown(source_path)
        
        # 2. Call VLM/LLM for initial Nine-Square Grid perception
        # In a real setup, we would send the image or the markdown to the LLM.
        # Here we simulate the perception step
        prompt = f"Analyze the following investment research content:\n\n{markdown_text or 'Image-based Content'}"
        if self.llm:
            perception_result_text = self.llm.chat_prompt(prompt)
        else:
            perception_result_text = None
        perception_result = {
            "status": "ok" if perception_result_text else "mocked",
            "raw_text": perception_result_text or "Sample analysis based on visual evidence.",
            "json_data": {
                "entities": [{"original_term": "海力士", "normalized_name": "SK Hynix"}]
            }
        }

        # 3. Slang Mapping & Normalization
        # Enrich the AI output with our local slang dictionary.
        slang_fragment = self.slang_mapper.get_canonical_json_fragment(markdown_text or "")
        
        # 4. Construct the Final Standardized Research Object (Step 1 Output)
        research_obj = {
            "research_id": f"res_{uuid.uuid4().hex[:8]}",
            "content_id": content_id,
            "entities": slang_fragment,
            "nine_grid_evaluation": {
                "macro": {"view": "AI perceived macro outlook", "intensity": 0.5},
                "technical": {"view": "AI perceived technical levels", "intensity": -0.2},
                "fundamental": {"view": "AI perceived fundamentals", "intensity": 0.8},
                "sentiment": {"creator_conviction": "high"}
            },
            "summary": "Full analysis summary generated by Perception Layer.",
            "parsing_status": "raw_parsed",
            "metadata": {
                "vlm_provider": "unified_llm",
                "input_type": content_type
            }
        }

        # 5. Filtering (RLHF Step 2 Preview)
        # Determine if this needs manual review (thresholding)
        intensity_score = max([abs(e.get('intensity', 0)) for e in research_obj['nine_grid_evaluation'].values() if isinstance(e, dict)])
        if intensity_score > 0.8:
            research_obj['review_required'] = True
            logging.info(f"Content marked for manual audit due to high intensity: {intensity_score}")

        return research_obj

    def save_research_object(self, obj: Dict[str, Any], output_path: Path):
        """
        Save the perception result as a JSON file.
        """
        output_path.parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            json.dump(obj, f, indent=2, ensure_ascii=False)
        logging.info(f"Saved research object to {output_path}")
